/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.src.main.java.http.project.networks.ii;

public class App {
    
    public static void main(String[] args) {
        System.out.println("Hello Github!");
    }
    
}
