/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package http.project.networks.ii;

import org.junit.jupiter.api.Test;

// import project.code.HttpClient;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void givenGreetingClient_whenServerRespondsWhenStarted_thenCorrect() {
        // HttpClient client = new HttpClient();
        // client.startConnection("127.0.0.1", 6666);
        // String response = client.sendMessage("hello server");
        // assertEquals("hello client", response);
    }
}