package http.project.networks.ii.tls;

import java.io.*;
import java.net.*;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.SignatureException;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.security.cert.CertificateExpiredException;
import java.security.cert.CertificateFactory;
import java.security.cert.CertificateNotYetValidException;
import java.security.cert.X509Certificate;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;

/**
 * This class represents the client hello message and all client operations of the TLS handshake
 */
public class ClientHello {
    private Socket socket;
    private DataOutputStream out;
    private DataInputStream in;
    private SecureRandom random;
    private Certificate certificate;
    private TlsShared tlsShared;
    private byte[] clientRandom;
    private byte[] serverRandom;
    /**
     * The symmetric key generated by the client
     */
    public SecretKey symmetricKey;

    /**
     * Constructor for the client TLS handshake´
     * The socket is created with the server name and port from GreetClient
     * @param serverName The server name
     * @param port The port number
     * @param tlsShared The shared data between the client and the server
     * @throws IOException if an I/O error occurs when creating the socket
     */
    public ClientHello(String serverName, int port, TlsShared tlsShared) throws IOException {
        socket = new Socket(serverName, port);
        out = new DataOutputStream(socket.getOutputStream());
        in = new DataInputStream(socket.getInputStream());
        random = new SecureRandom();
        certificate = null;
        this.tlsShared = tlsShared;
        this.clientRandom = new byte[32];
        this.serverRandom = new byte[32];
    }

    /**
     * Send the client hello message to the server
     * The client hello message contains the TLS version, the client random, and the cipher suite
     * The cipher suite is the symmetric encryption algorithm to be used
     * @throws IOException if an I/O error occurs when sending the message
     */
    public void sendClientHello() throws IOException {
        // TLS version (3.3 for TLSv1.3)
        out.writeByte(3);
        out.writeByte(3);
    
        //First random generated by the client
        random.nextBytes(this.clientRandom);
        out.write(this.clientRandom);

        // Cipher suite
        String cipherSuite = "TLS_RSA_WITH_AES_128_CBC_SHA";
        out.writeUTF(cipherSuite);
        
        out.flush();
    }

    /**
     * Validate the certificate received from the server
     * The certificate is validated by checking if it is expired or not yet valid
     * The certificate is also verified by the public key
     */
    public void validateCertificateFromServer() {
        try {
            // Read TLS version
            byte major = in.readByte();
            byte minor = in.readByte();

            //System.out.println("ServerHello: TLS version " + major + "." + minor);

            // Read server random
            in.readFully(this.serverRandom);

            // Read cipher suite
            String cipherSuite = in.readUTF();

            // Read certificate
            int certificateLength = in.readInt();
            byte[] certificateBytes = new byte[certificateLength];
            in.readFully(certificateBytes);

            certificate = CertificateFactory.getInstance("X.509")
                .generateCertificate(new ByteArrayInputStream(certificateBytes));
    
            //Not valid certificate will throw an exception
            PublicKey publicKey = certificate.getPublicKey();
            validateCertificate(publicKey);
            //System.out.println("CLIENT VERIFICATION SUCCESSFUL!. Selected cipher suite: " + cipherSuite+ ",\n Certificate: \n" + certificate.toString());
        } catch (IOException | CertificateException | InvalidKeyException | NoSuchAlgorithmException | NoSuchProviderException | SignatureException e) {
            e.printStackTrace();
        }
    }

    private void validateCertificate(PublicKey publicKey) throws CertificateException, 
                InvalidKeyException, NoSuchAlgorithmException, NoSuchProviderException, SignatureException {
                try {
                    X509Certificate x509Certificate = (X509Certificate) certificate;
                    x509Certificate.checkValidity();
                    x509Certificate.verify(publicKey);
                    //System.out.println("Client Verification: Certificate is valid.");
                } catch (CertificateExpiredException e) {
                    //System.out.println("Client Verification: Certificate is expired.");
                } catch (CertificateNotYetValidException e) {
                    //System.out.println("Client Verification: Certificate is not yet valid.");
                }
    }

    /**
     * Send the pre-master secret to the server ciphered with the server's certificate public key and generate the symmetric key
     * The pre-master secret is generated randomly and ciphered with the server's public key
     * @throws Exception if an error occurs when sending the pre-master secret or generating the symmetric key
     */
    public void sendPremasterSecret() throws Exception {
        // Generate pre-master secret
        byte[] preMasterSecret = new byte[48];
        random.nextBytes(preMasterSecret);
        Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
        cipher.init(Cipher.ENCRYPT_MODE, certificate.getPublicKey());
        byte[] encryptedPreMasterSecret = cipher.doFinal(preMasterSecret);

        // Send encrypted pre-master secret
        out.writeInt(encryptedPreMasterSecret.length);
        out.write(encryptedPreMasterSecret);
        out.flush();

        //Generate symmetric key
        tlsShared.setClientRandom(this.clientRandom);
        tlsShared.setServerRandom(this.serverRandom);
        tlsShared.generateSymmetricKey(preMasterSecret);
        this.symmetricKey = tlsShared.getSymmetricKey();
        //System.out.println("Client: Sent pre-master secret and have the symmetric key");
        //System.out.println("\nSymmetric key: " + Hex.encodeHexString(this.symmetricKey.getEncoded()));
    }
    
}